name: conn_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.1
  connectivity_plus: ^6.0.3
  network_info_plus: ^5.0.3
  permission_handler: ^11.3.1
  mqtt_client: ^10.3.0
  rxdart: ^0.28.0
  http: ^1.2.2
  wifi_iot: ^0.3.16
  file_picker: ^8.1.2
  archive: ^3.3.1

  # Dodane zależności do obsługi WebSocket
  web_socket_channel: ^2.3.0
  stream_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
